### ISSUE TITLE
支持显示/隐藏自定义属性

### ISSUE THREAD

**Issue by AdachiQ** [langzhou/note-attrs#4]
感谢开发了这么好用的挂件💕
当前版本在插入挂件后默认显示 updated属性，然而并不需要看这个属性，希望增加设置项，设置添加后默认显示的属性。

**Comment by langzhou** [comment]
> 感谢开发了这么好用的挂件💕 当前版本在插入挂件后默认显示 updated属性，然而并不需要看这个属性，希望增加设置项，设置添加后默认显示的属性。

后续计划添加隐藏/折叠属性的功能。
